version: '3.8'

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGODB_DATABASE: rickAndMorty
      

volumes:
  mongo_data:
